version: 2

updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "Microsoft.NET.Test.Sdk"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]